export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST'
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS'
export const LIST_MY_ORDERS_FAILURE = 'LIST_MY_ORDERS_FAILURE'
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET'

export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST'
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS'
export const LIST_ORDERS_FAILURE = 'LIST_ORDERS_FAILURE'
export const LIST_ORDERS_RESET = 'LIST_ORDERS_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAILURE = 'ORDER_DELIVER_FAILURE'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'
