export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'

export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'

export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'

export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'

export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'

export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'

export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE'

export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'
